import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import {Manrope} from 'next/font/google'


const manrope = Manrope({
  subsets: ['latin'], // Ensure the correct character subsets are used
  weight: ['400', '500', '700'], // Choose the font weights you need
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={manrope.className}
      >
        <div className="max-w-[1780px] mx-auto min-h-[10000px]">
          <Navbar/>
           {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
